// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn0e_fapSyS3OVMJmKN02-QhbGg_mCaN4',
    appId: '1:71159272849:web:b2e8b9f184263cbbfdf630',
    messagingSenderId: '71159272849',
    projectId: 'to-do-list-app-da49c',
    authDomain: 'to-do-list-app-da49c.firebaseapp.com',
    storageBucket: 'to-do-list-app-da49c.firebasestorage.app',
    measurementId: 'G-0GW50QDSFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg8zP9mSXECv2fJeYF7c7kVxARAotIPj4',
    appId: '1:71159272849:android:a1a00b267a90f0d7fdf630',
    messagingSenderId: '71159272849',
    projectId: 'to-do-list-app-da49c',
    storageBucket: 'to-do-list-app-da49c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7_j2i0aGR99YgHaaiMtFHmSVI4HpppQ',
    appId: '1:71159272849:ios:9a781112a3eb584dfdf630',
    messagingSenderId: '71159272849',
    projectId: 'to-do-list-app-da49c',
    storageBucket: 'to-do-list-app-da49c.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA7_j2i0aGR99YgHaaiMtFHmSVI4HpppQ',
    appId: '1:71159272849:ios:9a781112a3eb584dfdf630',
    messagingSenderId: '71159272849',
    projectId: 'to-do-list-app-da49c',
    storageBucket: 'to-do-list-app-da49c.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn0e_fapSyS3OVMJmKN02-QhbGg_mCaN4',
    appId: '1:71159272849:web:e478aad90af0196afdf630',
    messagingSenderId: '71159272849',
    projectId: 'to-do-list-app-da49c',
    authDomain: 'to-do-list-app-da49c.firebaseapp.com',
    storageBucket: 'to-do-list-app-da49c.firebasestorage.app',
    measurementId: 'G-YBKR16E0SG',
  );
}
